services:
  mysql:
    image: mysql:8.4
    restart: always
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: financial_control
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

networks:
    default:
        driver: bridge

volumes:
    mysql_data:
        driver: local